# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tie-Handle-HTTP
version:      0.01
version_from: lib/Tie/Handle/HTTP.pm
installdirs:  site
requires:
    Errno:                         0
    HTTP::Daemon:                  0
    HTTP::Request:                 0
    HTTP::Response:                0
    HTTP::Status:                  0
    LWP::UserAgent:                0
    Symbol:                        0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
